version: "3.9"

services:
  api:
    build: ./API
    container_name: car_api
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ENVIRONMENT: ${ENVIRONMENT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
    volumes:
      - ./API:/app
    ports:
      - "8000:8000"

  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    image: car-postgres-pgcron:16
    container_name: car_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ["postgres", "-c", "shared_preload_libraries=pg_cron"]
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./Database/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

volumes:
  db_data:
